container_image = metrics-conda.sif
executable = chtc-scripts/sc-rna/pseudotime-analysis/pseudotime.sh

Requirements = (Target.HasCHTCStaging == true)
transfer_input_files = \
    chtc-scripts/sc-rna/pseudotime-analysis/pseudotime.py, \
    chtc-scripts/sc-rna/pseudotime-analysis/pseudotime.sh, \
    ../../staging/nandwani2/MSSM_meta_obs.csv, \
    ../../staging/nandwani2/metadata_latest_oct5.csv, \
    metrics-conda.sif, \
    ../../staging/nandwani2/scFoundation_extracted.tar    
should_transfer_files   = YES

# Resources
request_cpus = 4
request_memory = 128GB
request_disk = 300GB
#request_gpus = 1

# Ensure GPU with sufficient VRAM
#Requirements = (CUDAGlobalMemoryMb >= 40000)
#Requirements = (CUDACapability >= 9.0)
#+WantGPULab = true
#+GPUJobLength = "long"

# Logging
stream_output           = true
log    = logs/pseudotime_$(Cluster)_$(Process).log
output = logs/pseudotime_$(Cluster)_$(Process).out
error  = logs/pseudotime_$(Cluster)_$(Process).err

