container_image = segformer.sif
executable = chtc-scripts/sc-rna/multi-class/train_cv.sh

Requirements = (Target.HasCHTCStaging == true)
transfer_input_files = \
    chtc-scripts/sc-rna/multi-class/train_cv.py, \
    chtc-scripts/sc-rna/multi-class/train_cv.sh, \
    chtc-scripts/sc-rna/multi-class/utils.py, \
    chtc-scripts/sc-rna/multi-class/phenotype_classification_files/r03x_split_seed42.pkl, \
    segformer.sif, \
    ../../staging/nandwani2/scFoundation_extracted.tar    
should_transfer_files   = YES

# Resources
request_cpus = 1
request_memory = 64GB
request_disk = 300GB
request_gpus = 1

# Ensure GPU with sufficient VRAM
Requirements = (CUDAGlobalMemoryMb >= 40000)
#Requirements = (CUDACapability >= 9.0)
+WantGPULab = true
+GPUJobLength = "long"

# Logging
stream_output           = true
log    = logs/multi-class_$(Cluster)_$(Process).log
output = logs/multi-class_$(Cluster)_$(Process).out
error  = logs/multi-class_$(Cluster)_$(Process).err

